kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "delivery.name.init" . }}
  labels:
    app: {{ template "delivery.name" . }}
    chart: {{ template "delivery.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.component }}
data:
{{ (.Files.Glob "init/*.json").AsConfig | indent 2 }}