apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cms.credentialsecret" . }}
  labels:
    app: {{ template "cms.name" . }}
    chart: {{ template "cms.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
type: Opaque
data:
  adminUser: {{ .Values.secret.credential.adminUser | b64enc | quote }}
  adminPassword: {{ .Values.secret.credential.adminPassword | b64enc | quote }}
  m2User: {{ .Values.secret.credential.m2User | b64enc | quote }}
  m2Password: {{ .Values.secret.credential.m2Password | b64enc | quote }}
