FROM @docker.base@:@parsedToolingVersion.majorVersion@.@parsedToolingVersion.minorVersion@.@parsedToolingVersion.incrementalVersion@
MAINTAINER @project.organization.name@  <@mailingLists.default.post@>
# Environment variables
ENV KARAF_VERSION="@grp.karaf.version@"
# Copy commands
COPY maven /