apiVersion: v1
kind: Service
metadata:
  name: "headless-delivery-cms-generic"
  labels:
    app: {{ template "cms.name" . }}
    chart: {{ template "cms.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
spec:
  selector:
    app: {{ template "cms.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpExternalPort }}
      targetPort: {{ .Values.service.httpInternalPort }}
      protocol: TCP
