apiVersion: v1
kind: Service
metadata:
  name: "client-delivery-elasticsearch-master"
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
spec:
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: {{ .Values.service.httpExternalPort }}
      targetPort: {{ .Values.service.httpInternalPort }}
      protocol: TCP
  {{- range .Values.service.customPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
  {{- end }}