apiVersion: v1
kind: Secret
metadata:
  name: {{ template "core.containersecret" . }}
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
type: kubernetes.io/dockercfg
data: 
  .dockercfg: {{ template "core.containerpullsecret" . }}