apiVersion: v1
kind: Secret
metadata:
  name: {{ template "generic.registrysecret" . }}
  labels:
    app: {{ template "generic.name" . }}
    chart: {{ template "generic.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
type: kubernetes.io/dockercfg
data: 
  .dockercfg: {{ template "generic.imagePullSecret" . }}
