apiVersion: v1
kind: Service
metadata:
  name: {{ template "generic.clientservice" . }}
  labels:
    app: {{ template "generic.name" . }}
    chart: {{ template "generic.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
spec:
  selector:
    app: {{ template "generic.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: {{ .Values.service.httpExternalPort }}
      targetPort: {{ .Values.service.httpInternalPort }}
      protocol: TCP
    - name: rmi-registry
      port: {{ .Values.service.rmiRegistryExternalPort }}
      targetPort: {{ .Values.service.rmiRegistryInternalPort }}
      protocol: TCP
