apiVersion: v1
kind: Service
metadata:
  name: "headless-delivery-elasticsearch-data"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chartname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.app.component }}
spec:
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  ports:
    - name: transport
      port: {{ .Values.service.transportExternalPort }}
      targetPort: {{ .Values.service.transportInternalPort }}
      protocol: TCP
  publishNotReadyAddresses: true
